// client/src/app/components/flight-results/flight-result-card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { FlightResult } from '../../types/flight';
import { parseDurationToMinutes } from '../../utils/filter-utils';

@Component({
  selector: 'app-flight-result-card',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="bg-white rounded-xl border shadow-sm p-4 cursor-pointer hover:shadow-md transition-shadow"
      [class.border-blue-400]="isSelected"
      [class.border-gray-200]="!isSelected"
      (click)="select.emit()"
    >
      <div class="flex items-center justify-between gap-4 flex-wrap">
        <!-- Airline -->
        <div class="flex items-center gap-2 min-w-[80px]">
          <span class="text-sm font-bold text-gray-800">{{ airline }}</span>
        </div>

        <!-- Departure -->
        <div class="text-center">
          <p class="text-lg font-bold text-gray-900">{{ departureTime }}</p>
          <p class="text-xs text-gray-500">{{ departureIata }}</p>
        </div>

        <!-- Duration + stops -->
        <div class="text-center flex-1">
          <p class="text-xs text-gray-500">{{ durationLabel }}</p>
          <div class="relative my-1 h-px bg-gray-300">
            <div class="absolute inset-0 flex items-center justify-center">
              <span class="bg-white px-1 text-xs text-gray-400">{{ stopsLabel }}</span>
            </div>
          </div>
        </div>

        <!-- Arrival -->
        <div class="text-center">
          <p class="text-lg font-bold text-gray-900">{{ arrivalTime }}</p>
          <p class="text-xs text-gray-500">{{ arrivalIata }}</p>
        </div>

        <!-- Price -->
        <div class="text-right min-w-[80px]">
          <p class="text-xl font-bold text-blue-600">{{ priceLabel }}</p>
          <p class="text-xs text-gray-400">{{ result.price.currency }}</p>
        </div>
      </div>
    </div>
  `,
})
export class FlightResultCardComponent {
  @Input({ required: true }) result!: FlightResult;
  @Input() isSelected = false;
  @Output() select = new EventEmitter<void>();

  get airline(): string {
    return this.result.validatingAirlineCodes[0] ?? '—';
  }

  get firstSeg() { return this.result.itineraries[0]?.segments[0]; }
  get lastSeg() {
    const segs = this.result.itineraries[0]?.segments ?? [];
    return segs[segs.length - 1];
  }

  get departureTime(): string {
    return this.firstSeg ? new Date(this.firstSeg.departure.at).toLocaleTimeString('it-IT', { hour: '2-digit', minute: '2-digit' }) : '—';
  }
  get arrivalTime(): string {
    return this.lastSeg ? new Date(this.lastSeg.arrival.at).toLocaleTimeString('it-IT', { hour: '2-digit', minute: '2-digit' }) : '—';
  }
  get departureIata(): string { return this.firstSeg?.departure.iataCode ?? '—'; }
  get arrivalIata(): string { return this.lastSeg?.arrival.iataCode ?? '—'; }

  get durationLabel(): string {
    const d = this.result.itineraries[0]?.duration ?? 'PT0M';
    const mins = parseDurationToMinutes(d);
    return `${Math.floor(mins / 60)}h ${mins % 60}m`;
  }

  get stopsLabel(): string {
    const segs = this.result.itineraries[0]?.segments ?? [];
    const stops = segs.length - 1;
    return stops === 0 ? 'Direct' : `${stops} stop${stops > 1 ? 's' : ''}`;
  }

  get priceLabel(): string {
    return parseFloat(this.result.price.grandTotal).toLocaleString('it-IT', {
      style: 'currency', currency: this.result.price.currency, maximumFractionDigits: 0,
    });
  }
}

// src/components/FlightResults/FlightResultCard.tsx
import React from 'react';
import type { FlightResult } from '../../types/flight';

interface FlightResultCardProps {
  result: FlightResult;
  onSelect: () => void;
  isSelected?: boolean;
}

/** Formats an ISO 8601 datetime string as "HH:MM" */
function formatTime(isoDatetime: string): string {
  const date = new Date(isoDatetime);
  const hh = String(date.getHours()).padStart(2, '0');
  const mm = String(date.getMinutes()).padStart(2, '0');
  return `${hh}:${mm}`;
}

/** Formats an ISO 8601 duration (e.g. "PT2H30M") as "2h 30m" */
export function formatDuration(isoDuration: string): string {
  const hoursMatch = isoDuration.match(/(\d+)H/);
  const minutesMatch = isoDuration.match(/(\d+)M/);
  const hours = hoursMatch ? parseInt(hoursMatch[1], 10) : 0;
  const minutes = minutesMatch ? parseInt(minutesMatch[1], 10) : 0;
  if (hours === 0) return `${minutes}m`;
  if (minutes === 0) return `${hours}h`;
  return `${hours}h ${minutes}m`;
}

/** Returns a human-readable stops label */
function formatStops(count: number): string {
  if (count === 0) return 'Direct';
  if (count === 1) return '1 stop';
  return `${count} stops`;
}

export const FlightResultCard: React.FC<FlightResultCardProps> = ({
  result,
  onSelect,
  isSelected = false,
}) => {
  const itinerary = result.itineraries[0];
  const segments = itinerary.segments;
  const firstSegment = segments[0];
  const lastSegment = segments[segments.length - 1];
  const stopCount = segments.length - 1;

  const airline = result.validatingAirlineCodes.join(', ');
  const departureTime = formatTime(firstSegment.departure.at);
  const arrivalTime = formatTime(lastSegment.arrival.at);
  const duration = formatDuration(itinerary.duration);
  const stops = formatStops(stopCount);
  const price = `${result.price.grandTotal} ${result.price.currency}`;

  return (
    <button
      type="button"
      onClick={onSelect}
      className={`w-full rounded-lg border p-4 text-left transition-colors hover:border-blue-400 hover:bg-blue-50 focus:outline-none focus:ring-2 focus:ring-blue-500 ${
        isSelected ? 'border-blue-500 bg-blue-50' : 'border-gray-200 bg-white'
      }`}
      aria-pressed={isSelected}
    >
      <div className="flex items-center justify-between gap-4">
        {/* Airline */}
        <div className="w-16 text-sm font-semibold text-gray-700">{airline}</div>

        {/* Times and route */}
        <div className="flex flex-1 items-center gap-2 text-center">
          <span className="text-lg font-bold text-gray-900">{departureTime}</span>
          <div className="flex flex-1 flex-col items-center">
            <span className="text-xs text-gray-500">{duration}</span>
            <div className="my-1 h-px w-full bg-gray-300" />
            <span className="text-xs text-gray-500">{stops}</span>
          </div>
          <span className="text-lg font-bold text-gray-900">{arrivalTime}</span>
        </div>

        {/* Price */}
        <div className="text-right">
          <span className="text-xl font-bold text-blue-600">{price}</span>
        </div>
      </div>
    </button>
  );
};

export default FlightResultCard;
