// src/components/PriceCalendar/PriceCalendar.tsx
import React, { useMemo } from 'react';
import { PriceCalendarEntry } from '../../types/flight';
import { computeIsLowest } from '../../utils/priceCalendarUtils';

interface PriceCalendarProps {
  entries: PriceCalendarEntry[];
  selectedDate: string;
  onDateSelect: (date: string) => void;
}

const WEEKDAYS = ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'];

function getMonthStart(year: number, month: number): Date {
  return new Date(year, month, 1);
}

/** Returns ISO date string "YYYY-MM-DD" for a local Date */
function toISODate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

/** Returns 0=Mon … 6=Sun offset for the first day of the month */
function firstDayOffset(year: number, month: number): number {
  const jsDay = getMonthStart(year, month).getDay(); // 0=Sun
  return (jsDay + 6) % 7; // convert to Mon=0
}

function daysInMonth(year: number, month: number): number {
  return new Date(year, month + 1, 0).getDate();
}

interface MonthGridProps {
  year: number;
  month: number;
  entryMap: Map<string, PriceCalendarEntry>;
  selectedDate: string;
  onDateSelect: (date: string) => void;
}

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

function MonthGrid({ year, month, entryMap, selectedDate, onDateSelect }: MonthGridProps) {
  const offset = firstDayOffset(year, month);
  const days = daysInMonth(year, month);

  const cells: (number | null)[] = [
    ...Array(offset).fill(null),
    ...Array.from({ length: days }, (_, i) => i + 1),
  ];

  // Pad to complete last row
  while (cells.length % 7 !== 0) cells.push(null);

  return (
    <div className="flex-1 min-w-[280px]">
      <h3 className="text-center font-semibold text-gray-700 mb-2">
        {MONTH_NAMES[month]} {year}
      </h3>
      <div className="grid grid-cols-7 gap-px text-xs">
        {WEEKDAYS.map((d) => (
          <div key={d} className="text-center font-medium text-gray-500 py-1">
            {d}
          </div>
        ))}
        {cells.map((day, idx) => {
          if (day === null) {
            return <div key={`empty-${idx}`} />;
          }

          const dateStr = toISODate(new Date(year, month, day));
          const entry = entryMap.get(dateStr);
          const isSelected = dateStr === selectedDate;
          const isUnavailable = !entry || entry.minPrice === null;
          const isLowest = entry?.isLowest ?? false;

          let cellClass =
            'flex flex-col items-center justify-center rounded p-1 cursor-pointer transition-colors min-h-[48px] ';

          if (isSelected) {
            cellClass += 'bg-blue-600 text-white ';
          } else if (isUnavailable) {
            cellClass += 'bg-gray-100 text-gray-400 cursor-not-allowed ';
          } else if (isLowest) {
            cellClass += 'bg-green-100 text-green-800 hover:bg-green-200 ';
          } else {
            cellClass += 'bg-white text-gray-700 hover:bg-blue-50 ';
          }

          return (
            <button
              key={dateStr}
              className={cellClass}
              disabled={isUnavailable}
              onClick={() => !isUnavailable && onDateSelect(dateStr)}
              aria-label={`${dateStr}${entry?.minPrice != null ? `, ${entry.currency} ${entry.minPrice}` : ', unavailable'}${isLowest ? ', lowest price' : ''}`}
              aria-pressed={isSelected}
            >
              <span className="font-medium">{day}</span>
              {entry?.minPrice != null ? (
                <span className="text-[10px] leading-tight">
                  {entry.currency} {entry.minPrice}
                </span>
              ) : (
                <span className="text-[10px] leading-tight text-gray-400">N/A</span>
              )}
            </button>
          );
        })}
      </div>
    </div>
  );
}

export function PriceCalendar({ entries, selectedDate, onDateSelect }: PriceCalendarProps) {
  const enriched = useMemo(() => computeIsLowest(entries), [entries]);

  const entryMap = useMemo(() => {
    const map = new Map<string, PriceCalendarEntry>();
    for (const e of enriched) map.set(e.date, e);
    return map;
  }, [enriched]);

  // Derive the two months to show from selectedDate
  const base = useMemo(() => {
    const d = selectedDate ? new Date(selectedDate + 'T00:00:00') : new Date();
    return { year: d.getFullYear(), month: d.getMonth() };
  }, [selectedDate]);

  const secondMonth = useMemo(() => {
    const m = base.month + 1;
    return m > 11
      ? { year: base.year + 1, month: 0 }
      : { year: base.year, month: m };
  }, [base]);

  return (
    <div className="bg-white rounded-lg shadow p-4">
      <div className="flex flex-wrap gap-6">
        <MonthGrid
          year={base.year}
          month={base.month}
          entryMap={entryMap}
          selectedDate={selectedDate}
          onDateSelect={onDateSelect}
        />
        <MonthGrid
          year={secondMonth.year}
          month={secondMonth.month}
          entryMap={entryMap}
          selectedDate={selectedDate}
          onDateSelect={onDateSelect}
        />
      </div>
      <div className="flex gap-4 mt-4 text-xs text-gray-500">
        <span className="flex items-center gap-1">
          <span className="inline-block w-3 h-3 rounded bg-green-100 border border-green-300" />
          Lowest price
        </span>
        <span className="flex items-center gap-1">
          <span className="inline-block w-3 h-3 rounded bg-gray-100 border border-gray-300" />
          Unavailable
        </span>
        <span className="flex items-center gap-1">
          <span className="inline-block w-3 h-3 rounded bg-blue-600" />
          Selected
        </span>
      </div>
    </div>
  );
}

export default PriceCalendar;

// client/src/app/components/price-calendar/price-calendar.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient, HttpParams } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import type { SearchParams, PriceCalendarEntry } from '../../types/flight';

@Component({
  selector: 'app-price-calendar',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-4">
      <div class="flex items-center justify-between mb-4">
        <button (click)="prevMonth()" [disabled]="!canGoPrev()"
          class="p-1 rounded hover:bg-gray-100 disabled:opacity-30 disabled:cursor-not-allowed transition-colors">
          ‹
        </button>
        <h3 class="text-sm font-semibold text-gray-700">{{ monthLabel() }}</h3>
        <button (click)="nextMonth()" [disabled]="!canGoNext()"
          class="p-1 rounded hover:bg-gray-100 disabled:opacity-30 disabled:cursor-not-allowed transition-colors">
          ›
        </button>
      </div>

      <!-- Day headers -->
      <div class="grid grid-cols-7 mb-1">
        @for (d of dayNames; track d) {
          <div class="text-center text-xs text-gray-400 font-medium py-1">{{ d }}</div>
        }
      </div>

      @if (isLoading()) {
        <div class="flex justify-center py-8">
          <div class="animate-spin rounded-full h-6 w-6 border-2 border-blue-200 border-t-blue-600"></div>
        </div>
      } @else {
        <!-- Calendar grid -->
        <div class="grid grid-cols-7 gap-px">
          <!-- Empty cells for first day offset -->
          @for (e of emptyStart(); track $index) {
            <div></div>
          }
          @for (entry of entries(); track entry.date) {
            @let isPast = entry.date < today;
            @let isSelected = entry.date === selectedDate;
            <button
              (click)="!isPast && entry.minPrice !== null && selectDate(entry.date)"
              [disabled]="isPast || entry.minPrice === null"
              class="flex flex-col items-center py-1 px-0.5 rounded text-center transition-colors text-xs"
              [class.bg-blue-600]="isSelected"
              [class.text-white]="isSelected"
              [class.bg-green-50]="!isSelected && entry.isLowest && !isPast"
              [class.text-green-700]="!isSelected && entry.isLowest && !isPast"
              [class.hover:bg-blue-50]="!isSelected && !isPast && entry.minPrice !== null"
              [class.opacity-30]="isPast"
              [class.cursor-not-allowed]="isPast || entry.minPrice === null"
            >
              <span class="font-medium">{{ dayNumber(entry.date) }}</span>
              @if (entry.minPrice !== null && !isPast) {
                <span class="text-[10px] leading-tight">
                  {{ formatPrice(entry.minPrice, entry.currency) }}
                </span>
              } @else if (!isPast) {
                <span class="text-[10px] text-gray-300">—</span>
              }
            </button>
          }
        </div>
      }

      <p class="mt-3 text-xs text-gray-400 text-center">
        🟢 Prezzo più basso del mese
      </p>
    </div>
  `,
})
export class PriceCalendarComponent implements OnChanges {
  @Input() searchParams: SearchParams | null = null;
  @Input() selectedDate = '';
  @Output() dateSelected = new EventEmitter<string>();

  private http = inject(HttpClient);

  dayNames = ['Lu', 'Ma', 'Me', 'Gi', 'Ve', 'Sa', 'Do'];
  today = new Date().toISOString().split('T')[0];

  currentYear = signal(new Date().getFullYear());
  currentMonth = signal(new Date().getMonth() + 1); // 1-based
  entries = signal<PriceCalendarEntry[]>([]);
  isLoading = signal(false);

  monthLabel = () => {
    const d = new Date(this.currentYear(), this.currentMonth() - 1, 1);
    return d.toLocaleDateString('it-IT', { month: 'long', year: 'numeric' });
  };

  canGoPrev = () => {
    const now = new Date();
    return this.currentYear() > now.getFullYear() ||
      (this.currentYear() === now.getFullYear() && this.currentMonth() > now.getMonth() + 1);
  };

  canGoNext = () => {
    const now = new Date();
    const maxYear = now.getFullYear();
    const maxMonth = now.getMonth() + 3; // max 3 months ahead
    const cur = this.currentYear() * 12 + this.currentMonth();
    const max = maxYear * 12 + maxMonth;
    return cur < max;
  };

  emptyStart = () => {
    const firstDay = new Date(this.currentYear(), this.currentMonth() - 1, 1).getDay();
    // Convert Sunday=0 to Monday=0 offset
    return Array(firstDay === 0 ? 6 : firstDay - 1).fill(0);
  };

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['searchParams'] && this.searchParams) {
      // Set initial month from departure date
      const dep = this.searchParams.departureDate;
      if (dep) {
        const d = new Date(dep);
        this.currentYear.set(d.getFullYear());
        this.currentMonth.set(d.getMonth() + 1);
      }
      this.loadCalendar();
    }
  }

  prevMonth(): void {
    if (!this.canGoPrev()) return;
    if (this.currentMonth() === 1) {
      this.currentMonth.set(12);
      this.currentYear.update((y) => y - 1);
    } else {
      this.currentMonth.update((m) => m - 1);
    }
    this.loadCalendar();
  }

  nextMonth(): void {
    if (!this.canGoNext()) return;
    if (this.currentMonth() === 12) {
      this.currentMonth.set(1);
      this.currentYear.update((y) => y + 1);
    } else {
      this.currentMonth.update((m) => m + 1);
    }
    this.loadCalendar();
  }

  loadCalendar(): void {
    if (!this.searchParams) return;
    this.isLoading.set(true);
    this.entries.set([]);

    const params = new HttpParams()
      .set('origin', this.searchParams.origin)
      .set('destination', this.searchParams.destination)
      .set('year', String(this.currentYear()))
      .set('month', String(this.currentMonth()))
      .set('cabin', this.searchParams.cabinClass)
      .set('adults', String(this.searchParams.passengers.adults));

    this.http.get<PriceCalendarEntry[]>(`${environment.apiBaseUrl}/api/price-calendar`, { params })
      .subscribe({
        next: (data) => { this.entries.set(data); this.isLoading.set(false); },
        error: () => { this.isLoading.set(false); },
      });
  }

  selectDate(date: string): void {
    this.dateSelected.emit(date);
  }

  dayNumber(date: string): number {
    return parseInt(date.split('-')[2], 10);
  }

  formatPrice(price: number, currency: string): string {
    return price.toLocaleString('it-IT', {
      style: 'currency', currency, maximumFractionDigits: 0,
    });
  }
}
