// client/src/app/components/common/loading-spinner.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-loading-spinner',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="flex justify-center items-center" [class]="containerClass">
      <div
        class="animate-spin rounded-full border-4 border-blue-200 border-t-blue-600"
        [class]="spinnerClass"
        role="status"
        aria-label="Loading"
      ></div>
    </div>
  `,
})
export class LoadingSpinnerComponent {
  @Input() size: 'sm' | 'md' | 'lg' = 'md';

  get spinnerClass(): string {
    return { sm: 'h-5 w-5', md: 'h-8 w-8', lg: 'h-12 w-12' }[this.size];
  }

  get containerClass(): string {
    return { sm: 'py-2', md: 'py-4', lg: 'py-8' }[this.size];
  }
}

// src/components/common/LoadingSpinner.tsx
import React from 'react';

interface LoadingSpinnerProps {
  size?: 'sm' | 'md' | 'lg';
}

const sizeClasses = {
  sm: 'h-4 w-4 border-2',
  md: 'h-8 w-8 border-2',
  lg: 'h-12 w-12 border-4',
};

export const LoadingSpinner: React.FC<LoadingSpinnerProps> = ({ size = 'md' }) => {
  return (
    <div
      role="status"
      aria-label="Loading"
      className={`animate-spin rounded-full border-blue-500 border-t-transparent ${sizeClasses[size]}`}
    />
  );
};

export default LoadingSpinner;
